

apache:
    #image: php:apache
    container_name: apache_symfony
    build: ./apache
    volumes:
    - "./src/:/var/www/html/appli/"
    #- "./apache2/sites-available/:/etc/apache2/sites-available/"
    links:
    - mysql
    ports:
    #- "4444:4444"
    - "80:80"
    - "443:443"
    - "8080:8080"
    privileged: true
mysql:
    #image: mysql:latest
    build: ./mysql
    container_name: mysql_symfony
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: "root"
    volumes:
        - dbdata:/var/lib/mysql
        - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - 3306:3306
