<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIwI4zH2\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIwI4zH2/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIwI4zH2.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIwI4zH2\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIwI4zH2\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IwI4zH2',
    'container.build_id' => '0785adb8',
    'container.build_time' => 1538266249,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIwI4zH2');
